name: Build
on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
jobs:
  # gosec:
  #   name: gosec
  #   uses: ellogroup/gosec-action@v1
  #   with:
  #     # The working directory to run gosec against. Default: .
  #     working-directory: '.'
  #     # The go package to run gosec against. Default: ./...
  #     go-package: './...'
  #     # Whether to install Go. Default: false
  #     go-install: true
  #     # The Go version to download (if necessary) and use
  #     go-version: '1.21.1'
  #     # Path to the go.mod or go.work file
  #     go-version-file: 'go.mod'
  #     # Used to specify the path to a dependency file - go.sum
  #     go-cache-dependency-path: 'go.sum'
  #     # Check for the latest available version. Default: false
  #     go-check-latest: true
  #     # Used to specify whether caching is needed. Default: true
  #     go-cache: true

  # tests:
  #   # needs: gosec
  #   runs-on: ubuntu-latest
  #   env:
  #     GO111MODULE: on
  #   steps:
  #     - name: Checkout Source
  #       uses: actions/checkout@v3
  #     - name: Run Gosec Security Scanner
  #       uses: securego/gosec@master
  #       with:
  #         args: ./...

  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: generate report
        run: go test -coverprofile=./cov.out ./... && go tool cover -html=cov.out -o coverage-report.html
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: bin
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
