name: Build
on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.1'

      - name: Run unit Tests
        run: |
          go test -coverprofile=./cov.out ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -no-fail -fmt=sonarqube -out report.json ./...  
        # run: |
        #   go get github.com/securego/gosec/cmd/gosec
        #   gosec -no-fail -fmt=sonarqube -out report.json ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}